sudo: false
language: python
python:
- '2.7'
- '3.6'
install: pip install tox-travis
script: tox
after_success:
- coveralls

jobs:
  include:
  - stage: deploy
    if: tag IS present
    script: echo 'Deploy to PyPi...'
    python: 3.6
    env: PBR_VERSION=$TRAVIS_TAG
    deploy:
      provider: pypi
      user: seignovert
      password:
        secure: VMXrHWp/IMmyOwAxoU31XHndG+4VbhIFuEDasHk4wiKcx5s1aSMhn/xKpWg/a5nWU2F3Wf082cnaxrBkhUkeqGjCnwsH0kr5vUGgACwIRxf8ZlVKwKSG2P7nKHrRf5dzVcTIDRU2zd47WWCs1lKevWKGRTcKWVqCRdS2wxE8ZMEn5TlYIvr5n8SObReJgPpGFaKF0CNIUCOG1jHaxtqOYUpVtkSJqkR9vI1AeQI/g3frtrOHTCLeR6KlUpoelXvsEeeMstJeJv2nEoD+kLvivHUXKvL6DhSvTf2FmUD7J3FdhgTbzoKsxN9s53XMrTpxswC78Imo/XarxaJhUGvYs9s1Wq/8qdSM4yHt0p7MOmp2OsjCMwP3yAgJTnNCxatIsfDJkBsiWlibYJfoB1L6Z+LDh0B+qivPjds0RQN+zsHUtP3GvJcN3+F33DIc7YrYK9tmWe4FSaEgSo7PFZWWgildjx8v5pMVC6shv+Ppdk2bKj6+KdBS3IBR1N+QPu8N6rjsupOBMF9u9reI2X9GdG/ngPSDGbHbwvBgcsvXEA2FBoj/Bjo+NI2/LVq/soN/0CxiQnqhgR41nnB0MZDFbMigCbYwzipzXp7HQnx9gKgty8k7Kb45DfyL344uyYxhb9tqUCkKqW7CkJ2QCFGpxALYnauUtYVVvSljcU5zIhg=
      skip_cleanup: true
      distributions: sdist bdist_wheel
      on:
        tags: true
        all_branches: true
